version: '3.0'
services:
  products:
    build: ./dockerfiles/python
    image: products
    container_name: products
    hostname: products
    restart: always
    volumes:
      - './products:/service'
    command: python3 /service/products.py
    ports:
      - '5001:5000'
  reviews:
    build: ./dockerfiles/python
    image: reviews
    container_name: reviews
    hostname: reviews
    restart: always
    volumes:
      - './reviews:/service'
    command: python3 /service/reviews.py
    ports:
      - '5002:5000'
  ratings:
    build: ./dockerfiles/python
    image: ratings
    container_name: ratings
    hostname: ratings
    restart: always
    volumes:
      - './ratings:/service'
    command: python3 /service/ratings.py
    ports:
      - '5003:5000'
  database:
    image: mysql
    container_name: database
    hostname: database
    restart: always
    ports:
      - '5004:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  files:
    image: files
    build: ./dockerfiles/nginx
    container_name: files
    hostname: files
    restart: always
    volumes:
      - './imagens:/usr/share/nginx/html'
    ports:
      - '5005:80'
